# Generated by Django 4.2.7 on 2023-11-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_copy',
            field=models.FileField(blank=True, null=True, upload_to='invoice_copies/'),
        ),
    ]
