# Generated by Django 4.2.7 on 2023-12-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0002_invoice_invoice_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceStatusTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100, verbose_name='Invoice No')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
            ],
        ),
        migrations.CreateModel(
            name='POTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_no', models.CharField(max_length=100, verbose_name='Purchase order no')),
                ('purchase_order_date', models.DateField(verbose_name='Purchase order date')),
                ('vendor_name', models.CharField(max_length=100, verbose_name='Vendor Name')),
                ('po_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('grn_no', models.CharField(max_length=100, verbose_name='GRN No')),
                ('invoice_no', models.CharField(max_length=100, verbose_name='Invoice No')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('link', models.FileField(blank=True, null=True, upload_to='invoice_copies/')),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
