# Generated by Django 4.2.7 on 2023-12-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0003_invoicestatustable_potable_remove_invoice_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potable',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='potable',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice No'),
        ),
    ]
