# Generated by Django 4.2.7 on 2023-12-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0004_alter_potable_invoice_date_alter_potable_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicestatustable',
            name='invoice_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice  due Date'),
        ),
        migrations.AddField(
            model_name='invoicestatustable',
            name='po_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PO No'),
        ),
        migrations.AddField(
            model_name='invoicestatustable',
            name='upload_invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoice_copies/'),
        ),
        migrations.AlterField(
            model_name='invoicestatustable',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='invoicestatustable',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
    ]
