# Generated by Django 4.2.7 on 2023-12-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0005_invoicestatustable_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicestatustable',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoicestatustable',
            name='payment_status',
            field=models.CharField(blank=True, default='Pending', max_length=50, null=True),
        ),
    ]
