# Generated by Django 4.2.7 on 2024-03-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0006_alter_invoicestatustable_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMasterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=100, verbose_name='Vendor ID')),
                ('Vendor_Name', models.CharField(max_length=100, verbose_name='Name')),
                ('Vendor_Address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('Contact_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Person')),
                ('gst_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='GST Details')),
            ],
        ),
    ]
