# Generated by Django 4.2.7 on 2024-03-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0007_vendormastertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=100, verbose_name='Ticket ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('vendor_id', models.CharField(max_length=100, verbose_name='Vendor ID')),
                ('ticket_category', models.CharField(max_length=100, verbose_name='Ticket Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('severity', models.CharField(max_length=50, verbose_name='Severity')),
            ],
        ),
    ]
