# Generated by Django 4.2.7 on 2024-03-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0008_issueticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueticket',
            name='id',
        ),
        migrations.AlterField(
            model_name='issueticket',
            name='ticket_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Ticket ID'),
        ),
        migrations.AlterField(
            model_name='issueticket',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor ID'),
        ),
    ]
